### ISSUE TITLE
Breadcrumb bar is missing

### ISSUE THREAD

**Issue by mrchief** [afonsof/jenkins-material-theme#15]
I see this in `style.less`. Is hiding it intentional? If so, then why?

```css
#breadcrumbBar {
  background-color: transparent;
  visibility: hidden
}
```
