### ISSUE TITLE
Overlapping text and icon in search bar on home page

### ISSUE THREAD

**Issue by risharaom** [afonsof/jenkins-material-theme#176]

**Comment by jcb-tn** [comment]
![image](https://user-images.githubusercontent.com/70505208/91688881-52b36680-eb63-11ea-9c31-e0d755844a65.png)

**Comment by NudeNULL** [comment]
Yes please fix it

**Comment by elawad** [comment]
FYI, a workaround is to apply this to Configure System > Theme > Extra CSS:
```css
#header #search-box {
  padding-left: 2em;
}
```
