### ISSUE TITLE
Pipeline replay editor is broken

### ISSUE THREAD

**Issue by bluesliverx** [afonsof/jenkins-material-theme#182]
I finally tracked this down to the font-family used on the editor. Removing the font-family applied from [our light blue theme](https://cdn.jsdelivr.net/gh/afonsof/jenkins-material-theme@gh-pages/dist/material-light-blue.css) results in the editor working again. The custom font family makes the cursor position wrong (as reported [here](https://github.com/ajaxorg/ace/issues/4431) and [here](https://issues.jenkins.io/browse/JENKINS-53200) ).

This appears to be the same problem as #48, though that was from 5 years ago and appears to be resolved (even though the issue was not closed). I figured opening a newer issue with a clearer description might be easier at this point.

**Comment by ahochsteger** [comment]
Until this is fixed, this is a workaround that can be added as extra CSS to the theme configuration of Jenkins:
```css
div.workflow-editor-wrapper,
textarea.ace_text-input,
div.ace_text-layer,
div.ace_line,
div.ace_line span,
div.ace_cursor-layer,
div.ace_editor > div:nth-child(7) > div:last-child {
    font-family: monospace !important
}
```
