### ISSUE TITLE
BUG - Console font is not Roboto Mono anymore

### ISSUE THREAD

**Issue by ylacaute** [afonsof/jenkins-material-theme#191]
The material theme do not use Roboto Mono anymore for the console (as the result it breaks my beautiful ascii arts haha)

The problem comes from here :

```css
:not(div.ace_editor) {
    font-family: Roboto,sans-serif !important;
    outline: 0;
}
```
If we remove !important, it is working
If we replace Roboto by Roboto Mono, it is working

I did'nt tested in a real Jenkins, but I think Roboto should be Roboto Mono, => [PR 190](https://github.com/afonsof/jenkins-material-theme/pull/190)

**Comment by senthil13** [comment]
+1, I am also facing the issue. 
but I would prefer removing the !important method. changing Roboto to Roboto Mono caused all fonts to change, but the first one only change the console output. 

Thanks
Senthil.

**Comment by ylacaute** [comment]
Indeed ! In fact we need to remove `!important` at 2 places :

```css
#main-panel > pre {
    font-family: Roboto Mono,monospace !important;
}

:not(div.ace_editor) {
    font-family: Roboto,sans-serif !important;
    outline: 0;
}
```

We can guess this `!important` has been added for reason, it is then complicated to do a PR.

You can see the result with this : https://github.com/ylacaute/jenkins-material-theme-blue-grey-fixed (personally I don't really see any difference, excepted the console is now monospace which is very important)
