### ISSUE TITLE
console color is gone in Jenkins 2.335

### ISSUE THREAD

**Issue by b-dean** [afonsof/jenkins-material-theme#193]
This started with Jenkins 2.335. Here's the [commit to the base style.less](https://github.com/jenkinsci/jenkins/commit/b97012a1f8e0968eb74c882b695673d7dc2cd559) in Jenkins that introduced some `!important` colors on all `pre` elements. See https://github.com/jenkinsci/jenkins/pull/6259

Here's a workaround you can add this extra css to your config:
```css
.console-output, .console-output pre {
    color: #e9eded !important;
}
```

Any fix for this should probably include the fix from #149

There may be other changes in those Jenkins 2.335 styles that break things.
