### ISSUE TITLE
Jenkins v2 pipeline stage view overlap

### ISSUE THREAD

**Issue by meier-christoph** [afonsof/jenkins-material-theme#73]
Hi,
there seems to be an issue with the pipeline stage view of jenkins v2 where the first stage overlaps the build info on the left (see attachment)

it only happens when width is over 1600px and some font sizes are updated

``` css
@media (min-width:1600px){
  body#jenkins.j-hide-left #main-panel{max-width:75%}
  body, table, form, input, td, th, p, textarea, select, #tasks .task
    {font-size:14px;}  
}
@media (min-width:2000px){
  body#jenkins.j-hide-left #main-panel{max-width:85%}
  body, table, form, input, td, th, p, textarea, select, #tasks .task
    {font-size:15px;}  
}
```

![jenkins](https://cloud.githubusercontent.com/assets/5633369/16517960/8f73a168-3f80-11e6-8367-e35997ce455f.PNG)

Thanks!

(I am using Chrome v51.0.2704.84 on Windows 10)
